### ISSUE TITLE
competence field is number is number

### ISSUE THREAD

**Issue by phadej** [planmill/api#11]
Though api says it should be string

- In `/users/` endpoint it seems to be string
- In `/users/:id` endpoint it seems to be number, is it enumeration here?

**Comment by petrukhnov-planmill** [comment]
Yes, it is a bug. 
We should create new field for competences that return meaningful data. Could you explain a bit, how you going to use it? E.g. do you need id there, name, both, etc?

**Comment by phadej** [comment]
For now the name is enough, but it would be useful to list all competences of the employee. I'd say situation is a bit similar as with capacity calendars.

**Comment by phadej** [comment]
Small update: At the moment we are interested in primary competence, and having it as enum (like e.g. contract type) would be the simplest.

**Comment by corvuscornix** [comment]
Hey,

actually this field is available through API already but is not perhaps the most obvious thing because of the inconsistencies. The information can be accessed through **/users/12345/meta** endpoint. For the competence it for some reason returns the options twice both caption-id and id-caption order but I guess that's not that bad thing considering that the table currently returns the caption. :-)
